### ISSUE TITLE
Does this work on Mono?

### ISSUE THREAD

**Issue by marcbarry** [hhblaze/SharmIPC#1]
I could not get this project to work correctly under Mono, please can you confirm that this works on Mono? I am testing under Mono `4.2.1` using Ubuntu 16.04 LTS.

The Mutex, as implemented on Mono does not provide the same inter-process synchronization like it does on Windows going back as far as version [2.8.0](http://www.mono-project.com/docs/about-mono/releases/2.8.0/#shared-handles-are-disabled-by-default).

**Comment by hhblaze** [comment]
Tested last time about year ago, was working. 
Now, sorry, have no info. I will remove MONO from the list until the next test.

**Comment by marcbarry** [comment]
I don't think it's just `4.2.1`. In `SharmIpcNetCore/ReaderWriterHandler.cs#L424` you're calling `System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen()`.

If you follow that through on the latest branch of Mono you get a `NotImplementedException` .. see https://github.com/mono/mono/blob/master/mcs/class/System.Core/System.IO.MemoryMappedFiles/MemoryMappedFile.cs#L399. The MemoryMappedFile class appears to be unsupported on Mono.

The Mutex class, as implemented on Mono also only provides inter-thread synchronization, not inter-process synchronization.

I would be very grateful if you could confirm when you get a chance, it is quite frustrating trying to understand why the "IPC engine for .NET MONO" doesn't seem to work on Mono :)

**Comment by hhblaze** [comment]
Interesting, since when they have removed that support. I am sure it was working after version 4. But anyway, thank you. I will remove MONO from that list.

**Comment by hhblaze** [comment]
Here they still had an implementation https://github.com/mono/mono/blob/a64dbc3e942a89c234bd4e7b4cfc1df9a43ce347/mcs/class/System.Core/System.IO.MemoryMappedFiles/MemoryMappedFile.cs
