### ISSUE TITLE
UWP really supported

### ISSUE THREAD

**Issue by oduis** [hhblaze/SharmIPC#7]
Are you sure UWP is really supported? I just tried it, did no work, and the documentation says Memory Mapped files are currently not supported by UWP:
https://github.com/MicrosoftDocs/windows-uwp/issues/458

**Comment by hhblaze** [comment]
Thanx, removed UWP from description.

**Comment by soumyamahunt** [comment]
I have tested support of creating MMF in UWP, but you have to declare `codeGeneration` capability in your manifest. While the [capability documentation](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#:~:text=Capabilities%20are%20used%20by%20UWP%20apps%20as%20well,by%20declaring%20capabilities%20in%20your%20app%27s%20package%20manifest.) mentions that, the MMF documentation doesn't mention it which causes confusion. Also, you can use your existing dotnet code for MMF as the support has been declared [while back](https://github.com/dotnet/corefx/commit/68949506e38203500c768fd2debbff73c0304b26).
