### ISSUE TITLE
the document and sample code need enhance

### ISSUE THREAD

**Issue by LeiYangGH** [hhblaze/SharmIPC#8]
i'm wondering how can such bad sample code get so many starts?

**Comment by hhblaze** [comment]
probably, because not for everybody it is so bad ;) though, you are free to fix the situation...

**Comment by hhblaze** [comment]
https://github.com/hhblaze/SharmIPC/blob/master/Process1/Process1/Form1.cs
https://github.com/hhblaze/SharmIPC/blob/master/Process2/Form1.cs
